import React from 'react';
import {Image, ImageSourcePropType, StyleSheet, View} from 'react-native';
import {EXACT_FOOD_ICONS} from './FoodIconRegistry';
import {findCatalogDishForMeal} from '../services/foodSearchService';

const FOOD_ICONS = {
  pho: require('../assets/food-icons/pho.png'),
  banhMi: require('../assets/food-icons/banh_mi.png'),
  burger: require('../assets/food-icons/burger.png'),
  pizza: require('../assets/food-icons/pizza.png'),
  spaghetti: require('../assets/food-icons/spaghetti.png'),
  lasagna: require('../assets/food-icons/lasagna.png'),
  tacos: require('../assets/food-icons/tacos.png'),
  burrito: require('../assets/food-icons/burrito.png'),
  sushi: require('../assets/food-icons/sushi.png'),
  ramen: require('../assets/food-icons/ramen.png'),
  udon: require('../assets/food-icons/udon.png'),
  soba: require('../assets/food-icons/soba.png'),
  tempura: require('../assets/food-icons/tempura.png'),
  tonkatsu: require('../assets/food-icons/tonkatsu.png'),
  curryRice: require('../assets/food-icons/curry_rice.png'),
  katsuCurry: require('../assets/food-icons/katsu_curry.png'),
  bibimbap: require('../assets/food-icons/bibimbap.png'),
  bulgogi: require('../assets/food-icons/bulgogi.png'),
  kimchi: require('../assets/food-icons/kimchi.png'),
  japchae: require('../assets/food-icons/japchae.png'),
  padThai: require('../assets/food-icons/pad_thai.png'),
  tomYum: require('../assets/food-icons/tom_yum.png'),
  greenCurry: require('../assets/food-icons/green_curry.png'),
  massamanCurry: require('../assets/food-icons/massaman_curry.png'),
  somTam: require('../assets/food-icons/som_tam.png'),
  mangoStickyRice: require('../assets/food-icons/mango_sticky_rice.png'),
  laksa: require('../assets/food-icons/laksa.png'),
  hainaneseChickenRice: require('../assets/food-icons/hainanese_chicken_rice.png'),
  harGow: require('../assets/food-icons/har_gow.png'),
  dimSum: require('../assets/food-icons/dim_sum.png'),
  pekingDuck: require('../assets/food-icons/peking_duck.png'),
  sweetSourPork: require('../assets/food-icons/sweet_sour_pork.png'),
  mapoTofu: require('../assets/food-icons/mapo_tofu.png'),
  kungPaoChicken: require('../assets/food-icons/kung_pao_chicken.png'),
  chowMein: require('../assets/food-icons/chow_mein.png'),
  friedRice: require('../assets/food-icons/fried_rice.png'),
  hotPot: require('../assets/food-icons/hot_pot.png'),
  sichuanNoodles: require('../assets/food-icons/sichuan_noodles.png'),
  xiaolongbao: require('../assets/food-icons/xiaolongbao.png'),
  jajangmyeon: require('../assets/food-icons/jajangmyeon.png'),
  friedChicken: require('../assets/food-icons/fried_chicken.png'),
  chickenWings: require('../assets/food-icons/chicken_wings.png'),
  steak: require('../assets/food-icons/steak.png'),
  ribs: require('../assets/food-icons/ribs.png'),
  schnitzel: require('../assets/food-icons/schnitzel.png'),
  fishAndChips: require('../assets/food-icons/fish_and_chips.png'),
  meatballs: require('../assets/food-icons/meatballs.png'),
  sausage: require('../assets/food-icons/sausage.png'),
  gyudon: require('../assets/food-icons/gyudon.png'),
  takoyaki: require('../assets/food-icons/takoyaki.png'),
  okonomiyaki: require('../assets/food-icons/okonomiyaki.png'),
  croissant: require('../assets/food-icons/croissant.png'),
  frenchFries: require('../assets/food-icons/french_fries.png'),
  sandwich: require('../assets/food-icons/sandwich.png'),
  clubSandwich: require('../assets/food-icons/club_sandwich.png'),
  wrap: require('../assets/food-icons/wrap.png'),
  falafel: require('../assets/food-icons/falafel.png'),
  hummus: require('../assets/food-icons/hummus.png'),
  shawarma: require('../assets/food-icons/shawarma.png'),
  kebab: require('../assets/food-icons/kebab.png'),
  biryani: require('../assets/food-icons/biryani.png'),
  butterChicken: require('../assets/food-icons/butter_chicken.png'),
  naan: require('../assets/food-icons/naan.png'),
  samosa: require('../assets/food-icons/samosa.png'),
  roganJosh: require('../assets/food-icons/rogan_josh.png'),
  dal: require('../assets/food-icons/dal.png'),
  chanaMasala: require('../assets/food-icons/chana_masala.png'),
  tandooriChicken: require('../assets/food-icons/tandoori_chicken.png'),
  paneer: require('../assets/food-icons/paneer.png'),
  dosa: require('../assets/food-icons/dosa.png'),
  arepa: require('../assets/food-icons/arepa.png'),
  ceviche: require('../assets/food-icons/ceviche.png'),
  empanada: require('../assets/food-icons/empanada.png'),
  feijoada: require('../assets/food-icons/feijoada.png'),
  poutine: require('../assets/food-icons/poutine.png'),
  gazpacho: require('../assets/food-icons/gazpacho.png'),
  paella: require('../assets/food-icons/paella.png'),
  risotto: require('../assets/food-icons/risotto.png'),
  gyoza: require('../assets/food-icons/gyoza.png'),
  quesadilla: require('../assets/food-icons/quesadilla.png'),
  ramenMiso: require('../assets/food-icons/ramen_miso.png'),
  ramenTonkotsu: require('../assets/food-icons/ramen_tonkotsu.png'),
  ramenShoyu: require('../assets/food-icons/ramen_shoyu.png'),
  ramenShio: require('../assets/food-icons/ramen_shio.png'),
  donut: require('../assets/food-icons/donut.png'),
  pancake: require('../assets/food-icons/pancake.png'),
  waffle: require('../assets/food-icons/waffle.png'),
  iceCream: require('../assets/food-icons/ice_cream.png'),
  cheesecake: require('../assets/food-icons/cheesecake.png'),
  tiramisu: require('../assets/food-icons/tiramisu.png'),
  baklava: require('../assets/food-icons/baklava.png'),
  churros: require('../assets/food-icons/churros.png'),
  springRolls: require('../assets/food-icons/spring_rolls.png'),
  satay: require('../assets/food-icons/satay.png'),
  curryLaksa: require('../assets/food-icons/curry_laksa.png'),
  banhXeo: require('../assets/food-icons/banh_xeo.png'),
  goiCuon: require('../assets/food-icons/goi_cuon.png'),
  rendang: require('../assets/food-icons/rendang.png'),
  adobo: require('../assets/food-icons/adobo.png'),
  haloHalo: require('../assets/food-icons/halo_halo.png'),
  comTam: require('../assets/food-icons/com_tam.png'),
  salad: require('../assets/food-icons/salad.png'),
  dessert: require('../assets/food-icons/dessert.png'),
  dumplings: require('../assets/food-icons/dumplings.png'),
} as const;
const ICON_BY_KEY: Record<string, ImageSourcePropType> = {
  'pho': FOOD_ICONS.pho,
  'banh_mi': FOOD_ICONS.banhMi,
  'burger': FOOD_ICONS.burger,
  'pizza': FOOD_ICONS.pizza,
  'spaghetti': FOOD_ICONS.spaghetti,
  'lasagna': FOOD_ICONS.lasagna,
  'tacos': FOOD_ICONS.tacos,
  'burrito': FOOD_ICONS.burrito,
  'sushi': FOOD_ICONS.sushi,
  'ramen': FOOD_ICONS.ramen,
  'udon': FOOD_ICONS.udon,
  'soba': FOOD_ICONS.soba,
  'tempura': FOOD_ICONS.tempura,
  'tonkatsu': FOOD_ICONS.tonkatsu,
  'curry_rice': FOOD_ICONS.curryRice,
  'katsu_curry': FOOD_ICONS.katsuCurry,
  'bibimbap': FOOD_ICONS.bibimbap,
  'bulgogi': FOOD_ICONS.bulgogi,
  'kimchi': FOOD_ICONS.kimchi,
  'japchae': FOOD_ICONS.japchae,
  'pad_thai': FOOD_ICONS.padThai,
  'tom_yum': FOOD_ICONS.tomYum,
  'green_curry': FOOD_ICONS.greenCurry,
  'massaman_curry': FOOD_ICONS.massamanCurry,
  'som_tam': FOOD_ICONS.somTam,
  'mango_sticky_rice': FOOD_ICONS.mangoStickyRice,
  'laksa': FOOD_ICONS.laksa,
  'hainanese_chicken_rice': FOOD_ICONS.hainaneseChickenRice,
  'har_gow': FOOD_ICONS.harGow,
  'dim_sum': FOOD_ICONS.dimSum,
  'peking_duck': FOOD_ICONS.pekingDuck,
  'sweet_sour_pork': FOOD_ICONS.sweetSourPork,
  'mapo_tofu': FOOD_ICONS.mapoTofu,
  'kung_pao_chicken': FOOD_ICONS.kungPaoChicken,
  'chow_mein': FOOD_ICONS.chowMein,
  'fried_rice': FOOD_ICONS.friedRice,
  'hot_pot': FOOD_ICONS.hotPot,
  'sichuan_noodles': FOOD_ICONS.sichuanNoodles,
  'xiaolongbao': FOOD_ICONS.xiaolongbao,
  'jajangmyeon': FOOD_ICONS.jajangmyeon,
  'fried_chicken': FOOD_ICONS.friedChicken,
  'chicken_wings': FOOD_ICONS.chickenWings,
  'steak': FOOD_ICONS.steak,
  'ribs': FOOD_ICONS.ribs,
  'schnitzel': FOOD_ICONS.schnitzel,
  'fish_and_chips': FOOD_ICONS.fishAndChips,
  'meatballs': FOOD_ICONS.meatballs,
  'sausage': FOOD_ICONS.sausage,
  'gyudon': FOOD_ICONS.gyudon,
  'takoyaki': FOOD_ICONS.takoyaki,
  'okonomiyaki': FOOD_ICONS.okonomiyaki,
  'croissant': FOOD_ICONS.croissant,
  'french_fries': FOOD_ICONS.frenchFries,
  'sandwich': FOOD_ICONS.sandwich,
  'club_sandwich': FOOD_ICONS.clubSandwich,
  'wrap': FOOD_ICONS.wrap,
  'falafel': FOOD_ICONS.falafel,
  'hummus': FOOD_ICONS.hummus,
  'shawarma': FOOD_ICONS.shawarma,
  'kebab': FOOD_ICONS.kebab,
  'biryani': FOOD_ICONS.biryani,
  'butter_chicken': FOOD_ICONS.butterChicken,
  'naan': FOOD_ICONS.naan,
  'samosa': FOOD_ICONS.samosa,
  'rogan_josh': FOOD_ICONS.roganJosh,
  'dal': FOOD_ICONS.dal,
  'chana_masala': FOOD_ICONS.chanaMasala,
  'tandoori_chicken': FOOD_ICONS.tandooriChicken,
  'paneer': FOOD_ICONS.paneer,
  'dosa': FOOD_ICONS.dosa,
  'arepa': FOOD_ICONS.arepa,
  'ceviche': FOOD_ICONS.ceviche,
  'empanada': FOOD_ICONS.empanada,
  'feijoada': FOOD_ICONS.feijoada,
  'poutine': FOOD_ICONS.poutine,
  'gazpacho': FOOD_ICONS.gazpacho,
  'paella': FOOD_ICONS.paella,
  'risotto': FOOD_ICONS.risotto,
  'gyoza': FOOD_ICONS.gyoza,
  'quesadilla': FOOD_ICONS.quesadilla,
  'ramen_miso': FOOD_ICONS.ramenMiso,
  'ramen_tonkotsu': FOOD_ICONS.ramenTonkotsu,
  'ramen_shoyu': FOOD_ICONS.ramenShoyu,
  'ramen_shio': FOOD_ICONS.ramenShio,
  'donut': FOOD_ICONS.donut,
  'pancake': FOOD_ICONS.pancake,
  'waffle': FOOD_ICONS.waffle,
  'ice_cream': FOOD_ICONS.iceCream,
  'cheesecake': FOOD_ICONS.cheesecake,
  'tiramisu': FOOD_ICONS.tiramisu,
  'baklava': FOOD_ICONS.baklava,
  'churros': FOOD_ICONS.churros,
  'spring_rolls': FOOD_ICONS.springRolls,
  'satay': FOOD_ICONS.satay,
  'curry_laksa': FOOD_ICONS.curryLaksa,
  'banh_xeo': FOOD_ICONS.banhXeo,
  'goi_cuon': FOOD_ICONS.goiCuon,
  'rendang': FOOD_ICONS.rendang,
  'adobo': FOOD_ICONS.adobo,
  'halo_halo': FOOD_ICONS.haloHalo,
  'com_tam': FOOD_ICONS.comTam,
  'salad': FOOD_ICONS.salad,
  'dessert': FOOD_ICONS.dessert,
  'dumplings': FOOD_ICONS.dumplings,
};


type MealLike = { name?: string; cuisine?: string; searchKeyword?: string; imageKey?: string; canonicalId?: string; familyId?: string; };
type Props = { meal?: MealLike | null; size?: number; rounded?: boolean; };

function normalize(value: string) { return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); }
function hasAny(text: string, values: string[]) { return values.some(value => text.includes(normalize(value))); }

const MATCHERS: Array<[ImageSourcePropType, string[]]> = [
  [FOOD_ICONS.ramenTonkotsu, ['tonkotsu ramen', 'ramen tonkotsu', '豚骨ラーメン']],
  [FOOD_ICONS.ramenMiso, ['miso ramen', 'ramen miso', '味噌ラーメン']],
  [FOOD_ICONS.ramenShoyu, ['shoyu ramen', 'ramen shoyu', '醤油ラーメン']],
  [FOOD_ICONS.ramenShio, ['shio ramen', 'ramen shio', '塩ラーメン']],
  [FOOD_ICONS.curryLaksa, ['curry laksa', 'laksa curry']],
  [FOOD_ICONS.hainaneseChickenRice, ['hainanese chicken rice', 'com ga hai nam', 'cơm gà hải nam']],
  [FOOD_ICONS.clubSandwich, ['club sandwich']],
  [FOOD_ICONS.fishAndChips, ['fish and chips', 'fish & chips']],
  [FOOD_ICONS.sweetSourPork, ['sweet and sour pork', 'sweet & sour pork']],
  [FOOD_ICONS.kungPaoChicken, ['kung pao chicken', 'gong bao chicken']],
  [FOOD_ICONS.sichuanNoodles, ['sichuan noodles', 'szechuan noodles', 'dan dan noodles']],
  [FOOD_ICONS.mangoStickyRice, ['mango sticky rice', 'khao niew mamuang']],
  [FOOD_ICONS.greenCurry, ['green curry', 'thai green curry', 'gaeng keow wan']],
  [FOOD_ICONS.massamanCurry, ['massaman curry', 'masaman curry']],
  [FOOD_ICONS.katsuCurry, ['katsu curry', 'curry katsu', 'tonkatsu curry', 'japanese curry']],
  [FOOD_ICONS.curryRice, ['curry rice', 'japanese curry rice', 'kare raisu']],
  [FOOD_ICONS.spaghetti, ['spaghetti', 'bolognese', 'pasta', 'mi y', 'mì ý', 'espagueti', 'спагетти']],
  [FOOD_ICONS.lasagna, ['lasagna', 'lasagne']],
  [FOOD_ICONS.tacos, ['taco', 'tacos', 'taqueria']],
  [FOOD_ICONS.burrito, ['burrito', 'burritos']],
  [FOOD_ICONS.pho, ['pho', 'phở', 'pho bo', 'pho ga']],
  [FOOD_ICONS.banhMi, ['banh mi', 'bánh mì', 'vietnamese sandwich']],
  [FOOD_ICONS.comTam, ['com tam', 'cơm tấm', 'broken rice']],
  [FOOD_ICONS.sushi, ['sushi', 'sashimi', '寿司']],
  [FOOD_ICONS.udon, ['udon', 'うどん']],
  [FOOD_ICONS.soba, ['soba', 'そば']],
  [FOOD_ICONS.tempura, ['tempura', '天ぷら']],
  [FOOD_ICONS.tonkatsu, ['tonkatsu', 'pork katsu', 'とんかつ']],
  [FOOD_ICONS.bibimbap, ['bibimbap', '비빔밥']],
  [FOOD_ICONS.bulgogi, ['bulgogi', '불고기']],
  [FOOD_ICONS.kimchi, ['kimchi', '김치']],
  [FOOD_ICONS.japchae, ['japchae', '잡채']],
  [FOOD_ICONS.padThai, ['pad thai', 'ผัดไทย']],
  [FOOD_ICONS.tomYum, ['tom yum', 'tom yam', 'ต้มยำ']],
  [FOOD_ICONS.somTam, ['som tam', 'papaya salad', 'ส้มตำ']],
  [FOOD_ICONS.laksa, ['laksa']],
  [FOOD_ICONS.harGow, ['har gow', 'har gao', 'shrimp dumpling']],
  [FOOD_ICONS.dimSum, ['dim sum', 'dimsum', 'yum cha']],
  [FOOD_ICONS.pekingDuck, ['peking duck', 'beijing duck']],
  [FOOD_ICONS.mapoTofu, ['mapo tofu', 'ma po tofu']],
  [FOOD_ICONS.chowMein, ['chow mein']],
  [FOOD_ICONS.friedRice, ['fried rice', 'com chien', 'cơm chiên', 'nasi goreng']],
  [FOOD_ICONS.hotPot, ['hot pot', 'hotpot', 'steamboat', 'lẩu', 'lau']],
  [FOOD_ICONS.xiaolongbao, ['xiaolongbao', 'xiao long bao', 'soup dumpling']],
  [FOOD_ICONS.jajangmyeon, ['jajangmyeon', 'jjajangmyeon', '짜장면']],
  [FOOD_ICONS.friedChicken, ['fried chicken', 'crispy chicken', 'ga ran', 'gà rán', 'ayam goreng']],
  [FOOD_ICONS.chickenWings, ['chicken wings', 'buffalo wings', 'wings']],
  [FOOD_ICONS.steak, ['steak', 'ribeye', 'sirloin', 'tenderloin', 'bit tet', 'bít tết']],
  [FOOD_ICONS.ribs, ['ribs', 'pork ribs', 'beef ribs', 'spare ribs']],
  [FOOD_ICONS.schnitzel, ['schnitzel', 'wiener schnitzel']],
  [FOOD_ICONS.meatballs, ['meatballs', 'meatball', 'polpette']],
  [FOOD_ICONS.sausage, ['sausage', 'sausages', 'bratwurst', 'wurst']],
  [FOOD_ICONS.gyudon, ['gyudon', 'beef bowl', '牛丼']],
  [FOOD_ICONS.takoyaki, ['takoyaki', 'たこ焼き']],
  [FOOD_ICONS.okonomiyaki, ['okonomiyaki', 'お好み焼き']],
  [FOOD_ICONS.croissant, ['croissant', 'banh sung bo', 'bánh sừng bò']],
  [FOOD_ICONS.frenchFries, ['french fries', 'fries', 'pommes frites', 'khoai tay chien']],
  [FOOD_ICONS.sandwich, ['sandwich', 'sandwiches']],
  [FOOD_ICONS.wrap, ['wrap', 'wraps']],
  [FOOD_ICONS.falafel, ['falafel']],
  [FOOD_ICONS.hummus, ['hummus', 'houmous']],
  [FOOD_ICONS.shawarma, ['shawarma', 'shawerma', 'gyro', 'doner', 'döner']],
  [FOOD_ICONS.kebab, ['kebab', 'kebap', 'kabob', 'shish kebab']],
  [FOOD_ICONS.biryani, ['biryani', 'biriyani']],
  [FOOD_ICONS.butterChicken, ['butter chicken', 'murgh makhani']],
  [FOOD_ICONS.naan, ['naan', 'nan bread']],
  [FOOD_ICONS.samosa, ['samosa', 'samosas']],
  [FOOD_ICONS.roganJosh, ['rogan josh']],
  [FOOD_ICONS.dal, ['dal', 'dhal', 'daal', 'lentil curry']],
  [FOOD_ICONS.chanaMasala, ['chana masala', 'chole']],
  [FOOD_ICONS.tandooriChicken, ['tandoori chicken', 'chicken tandoori']],
  [FOOD_ICONS.paneer, ['paneer', 'palak paneer', 'paneer tikka']],
  [FOOD_ICONS.dosa, ['dosa', 'masala dosa']],
  [FOOD_ICONS.arepa, ['arepa', 'arepas']],
  [FOOD_ICONS.ceviche, ['ceviche']],
  [FOOD_ICONS.empanada, ['empanada', 'empanadas']],
  [FOOD_ICONS.feijoada, ['feijoada']],
  [FOOD_ICONS.poutine, ['poutine']],
  [FOOD_ICONS.gazpacho, ['gazpacho']],
  [FOOD_ICONS.paella, ['paella']],
  [FOOD_ICONS.risotto, ['risotto']],
  [FOOD_ICONS.gyoza, ['gyoza', '餃子', '교자']],
  [FOOD_ICONS.quesadilla, ['quesadilla', 'quesadillas']],
  [FOOD_ICONS.donut, ['donut', 'doughnut', 'donuts']],
  [FOOD_ICONS.pancake, ['pancake', 'pancakes', 'hotcake']],
  [FOOD_ICONS.waffle, ['waffle', 'waffles']],
  [FOOD_ICONS.iceCream, ['ice cream', 'gelato', 'sorbet']],
  [FOOD_ICONS.cheesecake, ['cheesecake', 'cheese cake']],
  [FOOD_ICONS.tiramisu, ['tiramisu', 'tiramisù']],
  [FOOD_ICONS.baklava, ['baklava']],
  [FOOD_ICONS.churros, ['churro', 'churros']],
  [FOOD_ICONS.springRolls, ['spring roll', 'spring rolls', 'egg roll', 'cha gio', 'chả giò']],
  [FOOD_ICONS.satay, ['satay', 'sate', 'saté']],
  [FOOD_ICONS.banhXeo, ['banh xeo', 'bánh xèo']],
  [FOOD_ICONS.goiCuon, ['goi cuon', 'gỏi cuốn', 'summer rolls', 'fresh spring rolls']],
  [FOOD_ICONS.rendang, ['rendang', 'beef rendang']],
  [FOOD_ICONS.adobo, ['adobo', 'chicken adobo', 'pork adobo']],
  [FOOD_ICONS.haloHalo, ['halo halo', 'halo-halo']],
  [FOOD_ICONS.burger, ['burger', 'hamburger', 'cheeseburger']],
  [FOOD_ICONS.pizza, ['pizza']],
  [FOOD_ICONS.ramen, ['ramen', 'ラーメン']],
  [FOOD_ICONS.salad, ['salad', 'ensalada', 'salada', 'insalata', 'healthy bowl']],
  [FOOD_ICONS.dessert, ['dessert', 'cake', 'sweet', 'pudding']],
  [FOOD_ICONS.dumplings, ['dumpling', 'dumplings', 'jiaozi', 'mandu', 'เกี๊ยว']],
];

function detectIcon(meal?: MealLike | null): ImageSourcePropType {
  // Prefer stable catalog identity over an incoming imageKey. AI/cached suggestions
  // can carry stale image keys, while canonicalId and the bundled catalog remain
  // authoritative. This fixes cases such as Bún Riêu resolving to a salad image.
  const matchedDish = findCatalogDishForMeal(meal as any);
  const exactCandidates = [
    meal?.canonicalId,
    matchedDish?.id,
    matchedDish?.imageKey,
    meal?.imageKey,
    meal?.familyId,
  ].filter(Boolean).map(String);
  for (const exactKey of exactCandidates) {
    if (EXACT_FOOD_ICONS[exactKey]) return EXACT_FOOD_ICONS[exactKey];
  }
  if (matchedDish?.imageKey && ICON_BY_KEY[matchedDish.imageKey]) return ICON_BY_KEY[matchedDish.imageKey];
  if (meal?.imageKey && ICON_BY_KEY[meal.imageKey]) return ICON_BY_KEY[meal.imageKey];
  const text = normalize(`${meal?.name || ''} ${meal?.cuisine || ''} ${meal?.searchKeyword || ''}`);
  for (const [source, values] of MATCHERS) { if (hasAny(text, values)) return source; }
  if (hasAny(text, ['italian', 'italy'])) return FOOD_ICONS.spaghetti;
  if (hasAny(text, ['mexican', 'mexico'])) return FOOD_ICONS.tacos;
  if (hasAny(text, ['japanese', 'japan'])) return FOOD_ICONS.sushi;
  if (hasAny(text, ['korean', 'korea'])) return FOOD_ICONS.bibimbap;
  if (hasAny(text, ['thai', 'thailand'])) return FOOD_ICONS.padThai;
  if (hasAny(text, ['indian', 'india'])) return FOOD_ICONS.biryani;
  if (hasAny(text, ['vietnamese', 'vietnam'])) return FOOD_ICONS.pho;
  if (hasAny(text, ['middle eastern', 'arabic', 'turkish', 'mediterranean'])) return FOOD_ICONS.shawarma;
  if (hasAny(text, ['spanish', 'spain'])) return FOOD_ICONS.paella;
  if (hasAny(text, ['american', 'usa'])) return FOOD_ICONS.burger;
  return FOOD_ICONS.salad;
}

export function FoodAssetIcon({meal, size = 64, rounded = true}: Props) {
  const source = detectIcon(meal);
  return (
    <View style={[styles.shell, {width: size, height: size, borderRadius: rounded ? size / 2.6 : 24}]}>
      <Image source={source} resizeMode="contain" style={{width: size * 0.96, height: size * 0.96}} />
    </View>
  );
}

const styles = StyleSheet.create({ shell: {alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.96)'} });